/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nilantunes (https://sketchfab.com/nilantunes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dna-vr-interactive-animation-c9a926f139044470ad3fb053c66ad71e
Title: DNA VR Interactive Animation
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Dna(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/miles_morales_spiderman_-_spiderverse.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.341}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.aiStandardSurface24SG}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.set19}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials.set22}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/miles_morales_spiderman_-_spiderverse.glb')
